# Generated by Django 3.2.25 on 2025-02-15 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('position', models.CharField(blank=True, max_length=200, null=True)),
                ('responsibilities', models.TextField(blank=True)),
                ('Requirements', models.TextField(blank=True)),
                ('Benefits', models.TextField(blank=True)),
                ('footmessage', models.TextField(blank=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('jobID', models.CharField(blank=True, max_length=14, null=True, verbose_name='Job ID')),
            ],
        ),
    ]
