# Generated by Django 3.2.25 on 2025-02-15 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='introduction',
            field=models.TextField(blank=True),
        ),
    ]
