# Generated by Django 3.2.25 on 2025-02-18 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_job_introduction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Your Name')),
                ('phone', models.CharField(blank=True, max_length=200, null=True, verbose_name='Phone Number')),
                ('email', models.CharField(blank=True, max_length=200, null=True, verbose_name='Your Email')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('date_send', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
